# Generated by Django 5.0.14 on 2025-07-13 02:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_initial'),
        ('core', '0002_initial'),
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloPreguntas',
            fields=[
                ('id_modulo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del periodo de evaluación', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del periodo de evaluación', null=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del periodo de evaluación')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del periodo de evaluación')),
                ('fecha_comision', models.DateField(help_text='Fecha de reunión de comisión para revisión')),
                ('fecha_cierre', models.DateField(help_text='Fecha de cierre definitivo y publicación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de inicio'), ('activo', 'Activo'), ('revision', 'En revisión por comisión'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada')], default='borrador', max_length=20)),
                ('comentario_general', models.TextField(blank=True, help_text='Comentario general sobre la evaluación', null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docentes.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='PreguntaModulo',
            fields=[
                ('id_pregunta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregunta', models.TextField(max_length=1000)),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.modulopreguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterio', models.CharField(blank=True, max_length=100, null=True)),
                ('puntuacion', models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.evaluacion')),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.preguntamodulo')),
            ],
        ),
    ]
